name = "v2ray-worker"
main = "src/worker.ts"
compatibility_date = "2024-05-29"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "settings", 878868911aeb4e4bb4993c869125996f = "alpHa-kv" }
]
